// ignore_for_file: non_constant_identifier_names

import 'package:e_commerce_car/models/country.dart';

List<Country> CountryList = [
  Country(name: 'angel'),
  Country(name: 'bubbles'),
  Country(name: 'shimmer'),
  Country(name: 'angelic'),
  Country(name: 'bubbly'),
  Country(name: 'glimmer'),
  Country(name: 'baby'),
  Country(name: 'pink'),
  Country(name: 'little'),
  Country(name: 'butterfly'),
  Country(name: 'sparkly'),
  Country(name: 'doll'),
  Country(name: 'sweet'),
  Country(name: 'sparkles'),
  Country(name: 'dolly'),
  Country(name: 'sweetie'),
  Country(name: 'sprinkles'),
  Country(name: 'lolly'),
  Country(name: 'princess'),
  Country(name: 'fairy'),
  Country(name: 'honey'),
  Country(name: 'snowflake'),
  Country(name: 'pretty'),
  Country(name: 'sugar'),
  Country(name: 'cherub'),
  Country(name: 'lovely'),
  Country(name: 'blossom'),
  Country(name: 'Ecophobia'),
  Country(name: 'Hippophobia'),
  Country(name: 'Scolionophobia'),
  Country(name: 'Ergophobia'),
  Country(name: 'Musophobia'),
  Country(name: 'Zemmiphobia'),
  Country(name: 'Geliophobia'),
  Country(name: 'Tachophobia'),
  Country(name: 'Hadephobia'),
  Country(name: 'Radiophobia'),
  Country(name: 'Turbo Slayer'),
  Country(name: 'Cryptic Hatter'),
  Country(name: 'Crash TV'),
  Country(name: 'Blue Defender'),
  Country(name: 'Toxic Headshot'),
  Country(name: 'Iron Merc'),
  Country(name: 'Steel Titan'),
  Country(name: 'Stealthed Defender'),
  Country(name: 'Blaze Assault'),
  Country(name: 'Venom Fate'),
  Country(name: 'Dark Carnage'),
  Country(name: 'Fatal Destiny'),
  Country(name: 'Ultimate Beast'),
  Country(name: 'Masked Titan'),
  Country(name: 'Frozen Gunner'),
  Country(name: 'Bandalls'),
  Country(name: 'Wattlexp'),
  Country(name: 'Sweetiele'),
  Country(name: 'HyperYauFarer'),
  Country(name: 'Editussion'),
  Country(name: 'Experthead'),
  Country(name: 'Flamesbria'),
  Country(name: 'HeroAnhart'),
  Country(name: 'Liveltekah'),
  Country(name: 'Linguss'),
  Country(name: 'Interestec'),
  Country(name: 'FuzzySpuffy'),
  Country(name: 'Monsterup'),
  Country(name: 'MilkA1Baby'),
  Country(name: 'LovesBoost'),
  Country(name: 'Edgymnerch'),
  Country(name: 'Ortspoon'),
  Country(name: 'Oranolio'),
  Country(name: 'OneMama'),
  Country(name: 'Dravenfact'),
  Country(name: 'Reallychel'),
  Country(name: 'Reakefit'),
  Country(name: 'Popularkiya'),
  Country(name: 'Breacche'),
  Country(name: 'Blikimore'),
  Country(name: 'StoneWellForever'),
  Country(name: 'Simmson'),
  Country(name: 'BrightHulk'),
  Country(name: 'Bootecia'),
  Country(name: 'Spuffyffet'),
  Country(name: 'Rozalthiric'),
  Country(name: 'Bookman')
];
